### ISSUE TITLE
ValueError: unconverted data remains: , 2020

### ISSUE THREAD

**Issue by sashih** [alvarobartt/covid-daily#5]
In the function _data_ of _covid.py_, the _value in chart['xAxis']['categories']_ is now in the format of Feb 15, 2020, for example, so there is no need to add ', 2020' in datetime.strptime(). 
Suggestion: 
y = [datetime.strptime(value, '%b %d, %Y') for value in chart['xAxis']['categories']]

**Comment by RafaelMendozaArriaga** [comment]
Hi I'm having the same issue.... ValueError: unconverted data remains: , 2020

**Comment by akhilarj** [comment]
Same issue

**Comment by alvarobartt** [comment]
Hi again @sashih, @RafaelMendozaArriaga and @akhilarj! Thank you all for reporting this issue, can anyone send me the sample call that keeps having the error?

Will try to fix it this afternoon as as far as I could test that was solved for the sample call you sent me the other day, anyway, I'll debug it again so as to spot the error there! 🤗

**Comment by sashih** [comment]
I run it in ipython --pylab after importing covid_daily module. Line 162 in covid.py is what I use to fix the bug. 

![image](https://user-images.githubusercontent.com/48677970/105691560-5bed0780-5f38-11eb-90ad-b75c964fe1c1.png)

**Comment by alvarobartt** [comment]
Hi @sashih could you please try to update the package with:

```bash
pip install covid_daily==1.2
```

And then trying to retrieve the information as it follows:

```python
import covid_daily

data = covid_daily.data(country='taiwan', chart='graph-cases-daily', as_json=False)
```

Thank you! 🤗

**Comment by alvarobartt** [comment]
Anyway, does the line 162 of your `covid.py` file solve the problem? As I was not sure whether the graphs provided by Worldometers.info had the full date or just the date in format: `%m %d`.

Just let me know so that I can fix it ASAP! 👍🏻

**Comment by RafaelMendozaArriaga** [comment]
![Screen Shot 2021-01-25 at 8 26 53 AM](https://user-images.githubusercontent.com/57351166/105719388-d8a3c580-5ee7-11eb-817a-b695eff47c88.png)
![Screen Shot 2021-01-25 at 8 30 11 AM](https://user-images.githubusercontent.com/57351166/105719399-da6d8900-5ee7-11eb-9e47-ca9a72dd6d2b.png)

Hi Alvaro, 

 Thank you for doing this..  please see that even verifying version 1.2 was installed (I uninstalled and re-installed the version, see the “version” printout in the log) the error still exist. 

I’m also printing the log from the installation, perhaps there is a library missing? 

Thanks
Rafa

**Comment by alvarobartt** [comment]
No problem @RafaelMendozaArriaga, thanks for sharing the output! I'll check it later today and if I manage to fix it I'll update the code and generate a newer version so as to solve this as this issue is affecting more users 💪🏻

**Comment by alvarobartt** [comment]
Check the new release, this should be fixed now! 🤗 @sashih @RafaelMendozaArriaga @akhilarj 

```bash
pip install covid_daily==1.3.0
```

**Comment by enigmamr** [comment]
1.3.0 works! 2021 year is correct now (US data)
![image](https://user-images.githubusercontent.com/1919473/105771317-3c90b300-5f15-11eb-9e7a-2c5d47ef2142.png)

**Comment by RafaelMendozaArriaga** [comment]
Thanks a lot, 


I will test it shortly.. 
Rafa

**Comment by alvarobartt** [comment]
Cool! Remember to star the repo, follow me here on GitHub and on Twitter at https://twitter.com/alvarobartt so as to get notified from all the updates and projects I'm working on! ⭐

**Comment by RafaelMendozaArriaga** [comment]
Hi Alvaro, it works now,  thanks!

**Comment by RafaelMendozaArriaga** [comment]
Alvaro, 


 Quick question,   why did the version 1.1  and 1.0  broke as well after  the version 1.2 was created?… 

  Did you modify both codes?.. I tried to go back to version 1.1 and it was throwing the same error.     

  I’m asking because if I add this to an automated process, I’d like to know whether there is any risk the that a newer, version (whenever arrives) if it contains a bug or something, would affect previous versions as well? 

Thanks 
Rafa

**Comment by akhilarj** [comment]
works now. Thanks much for the quick fix.

**Comment by alvarobartt** [comment]
Hi @RafaelMendozaArriaga that issue keeps on happening on those versions as Worldometers.info modified how the dates are displayed, which means that the conversion to `%M %d, %Y` is no longer needed. So on, those versions are deprecated due to a website update on Worldometers.info, that, as you may know, I can't do anything about it 😩 

This means that the master version will always be working as it's not uploaded to PyPI until the build success, so the way to trust this is to make sure that once the website is modified someone reports the issue so that I can fix it ASAP 👍🏻 

Just install the new version and that should work properly!

```bash
pip install covid_daily==1.3.0
```

Or just upgrade the current version you have!

```
pip install covid_daily --upgrade
```
